"""Updated with task_id

Revision ID: 578d09484569
Revises: 58e3ea2a9b96
Create Date: 2024-09-08 12:03:42.403449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578d09484569'
down_revision = '58e3ea2a9b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    with op.batch_alter_table('video_operations', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
